### ISSUE TITLE
Can't work for me

### ISSUE THREAD

**Issue by MartinXM** [Fire-Proof/LoLVRSpectate#6]
I have run vorpx in normal mode, turn on steamvr and LOL, wait fully load the game and open LOLVRSpectate.exe . It looks fun on my computer screen but no game on my HMD. Then I try run vorpx in administrator mode. It works in my HMD, but blackscreen on my pc, and when I open LOLVRSpectate.exe, the game stuck.

**Comment by nickolaj-jepsen** [comment]
Are you sure that you have added the LOLVRSpectate.exe to the VorpX exception list found [here](http://i.imgur.com/NO9g62K.png)? 

Also when running vorpX, most games will display a black screen, to change the you have to use the ingame vorpX settings menu, you can access this by pressing the delete key and finding the setting called "Direct Mode Show Original" and turning it on

**Comment by nickolaj-jepsen** [comment]
I'm gonna assume this fixed it.
