### ISSUE TITLE
cant get pid from b'LOL

### ISSUE THREAD

**Issue by vrxiaochouyu** [Fire-Proof/LoLVRSpectate#7]
what‘s wrong with it？

**Comment by vrxiaochouyu** [comment]
LOLVRSpectate.memorpy.process.processExcrption: can't get pid from name b' League of Legends

**Comment by vrxiaochouyu** [comment]
new error 299 in ReadProcessMemory（0000000,4，read=0）

**Comment by nickolaj-jepsen** [comment]
Hello, sorry for the late response, what client are you using, and what patch are you on? i have only tested i with the EUW client, there might be some issues if you use a non-english client.

**Comment by vrxiaochouyu** [comment]
@Fire-Proof i use Chinese client and American client ,but it's all fail. and i make sure use enlish paths.
it happen ：cant get pid from b'LOL .
and then i reload LOL, and then happen： error 299 in ReadProcessMemory（0000000,4，read=0）

**Comment by nickolaj-jepsen** [comment]
I have just released a new version, try and see if it has fixed your issues

**Comment by nickolaj-jepsen** [comment]
Woops, forgot to publish the new version on github, sorry!

**Comment by nickolaj-jepsen** [comment]
I assume this fixed the issue

**Comment by Xrave** [comment]
Does not seem to be fixed on current NA client.
